spring:
  cloud:
    gateway:
      routes:
        - id: event
          uri: http://localhost:8082/
          predicates:
            - Path=/event
        - id: employees
            uri: http://localhost:8081/
            predicates:
              - Path=/Timesheet
        - id: 3
            uri: http://localhost:8083/
            predicates:
              - Path=/**
        - id: 4
            uri: http://localhost:8084/
            predicates:
              - Path=/**
